### ISSUE TITLE
Video did not stream

### ISSUE THREAD

**Issue by 4nkit-5hukla** [Abdisalan/blog-code-examples#14]
mongo-http-video

Borwser Opera Gx, Chromium, Google Chrome
I even update all the package dependency

events.js:377
      throw er; // Unhandled 'error' event
      ^

MongoInvalidArgumentError: Stream start (63537152) must not be greater than stream end (0)
    at handleStartOption (E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\gridfs\download.js:292:19)
    at E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\gridfs\download.js:241:36
    at E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\utils.js:510:9
    at E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\cursor\abstract_cursor.js:480:68
    at E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\utils.js:510:9
    at completeEndSession (E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\sessions.js:147:17)
    at E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\sessions.js:157:13
    at maybePromise (E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\utils.js:496:5)
    at ClientSession.endSession (E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\sessions.js:133:41)
    at cleanupCursor (E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\cursor\abstract_cursor.js:533:32)
Emitted 'error' event on GridFSBucketReadStream instance at:
    at E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\gridfs\download.js:244:27
    at E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\utils.js:510:9
    [... lines matching original stack trace ...]
    at cleanupCursor (E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\cursor\abstract_cursor.js:533:32)
    at E:\Node\blog-code-examples\mongo-http-video\node_modules\mongodb\lib\cursor\abstract_cursor.js:480:24

**Comment by krynv** [comment]
This is likely due to the fact that you updated all of the package dependencies. Namely the `mongodb` provider.
You need to use the same version of `mongodb` as listed in the project `package.json` file (sub `4.1.4`). 

I don't know what changes to make in order to utilise the latest version of mongo however. Perhaps @Abdisalan can shed some light on this

**Comment by kolyathedev** [comment]
above worked for me

**Comment by Abdisalan** [comment]
thanks @krynv
